<a href="https://colab.research.google.com/github/yisuznazi/juegosAjedrez/blob/main/ajedrez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


20.juegos de ajedrez


Distribución de ELO de jugadores blancos vs negros
¿Quién gana más, blancas o negras?
Partidas rated vs no rated

Análisis de aperturas columna eco y opening_name

¿Qué aperturas tienen mayor tasa de victoria?
¿Las aperturas más largas opening_ply favorecen a alguien?

Correlaciones interesantes

¿Más turnos = partidas más igualadas en ELO?
¿Diferencia de ELO predice el resultado?
¿El tiempo de control increment_code afecta quién gana?

Minería de texto columna moves

Movimientos más frecuentes en las primeras jugadas
Patrones de jugadas ganadoras

Clasificación / ML opcional

Predecir el ganador con white_elo, black_elo, opening_name, turns

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
df=pd.read_csv('games.csv')

In [6]:
df.head()

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
0,TZJHLljE,False,1.504210e+12,1.504210e+12,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5
1,l1NXvwaE,True,1.504130e+12,1.504130e+12,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4
2,mIICvQHh,True,1.504130e+12,1.504130e+12,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3
3,kWKvrqYL,True,1.504110e+12,1.504110e+12,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3
4,9tXo1AUZ,True,1.504030e+12,1.504030e+12,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5

In [7]:
df.tail(
)

,id,rated,created_at,last_move_at,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
20053,EfqH7VVH,True,1.499791e+12,1.499791e+12,24,resign,white,10+10,belcolt,1691,jamboger,1220,d4 f5 e3 e6 Nf3 Nf6 Nc3 b6 Be2 Bb7 O-O Be7 Ne5...,A80,Dutch Defense,2
20054,WSJDhbPl,True,1.499698e+12,1.499699e+12,82,mate,black,10+0,jamboger,1233,farrukhasomiddinov,1196,d4 d6 Bf4 e5 Bg3 Nf6 e3 exd4 exd4 d5 c3 Bd6 Bd...,A41,Queen's Pawn,2
20055,yrAas0Kj,True,1.499698e+12,1.499698e+12,35,mate,white,10+0,jamboger,1219,schaaksmurf3,1286,d4 d5 Bf4 Nc6 e3 Nf6 c3 e6 Nf3 Be7 Bd3 O-O Nbd...,D00,Queen's Pawn Game: Mason Attack,3
20056,b0v4tRyF,True,1.499696e+12,1.499697e+12,109,resign,white,10+0,marcodisogno,1360,jamboger,1227,e4 d6 d4 Nf6 e5 dxe5 dxe5 Qxd1+ Kxd1 Nd5 c4 Nb...,B07,Pirc Defense,4
20057,N8G2JHGG,True,1.499643e+12,1.499644e+12,78,mate,black,10+0,jamboger,1235,ffbob,1339,d4 d5 Bf4 Na6 e3 e6 c3 Nf6 Nf3 Bd7 Nbd2 b5 Bd3...,D00,Queen's Pawn Game: Mason Attack,3

In [9]:
df.dtypes

id                 object
rated                bool
created_at        float64
last_move_at      float64
turns               int64
victory_status     object
winner             object
increment_code     object
white_id           object
white_rating        int64
black_id           object
black_rating        int64
moves              object
opening_eco        object
opening_name       object
opening_ply         int64
dtype: object

In [10]:
df.shape

(20058, 16)

In [11]:
df.isnull().sum()

id                0
rated             0
created_at        0
last_move_at      0
turns             0
victory_status    0
winner            0
increment_code    0
white_id          0
white_rating      0
black_id          0
black_rating      0
moves             0
opening_eco       0
opening_name      0
opening_ply       0
dtype: int64

In [12]:
df.columns

Index(['id', 'rated', 'created_at', 'last_move_at', 'turns', 'victory_status',
       'winner', 'increment_code', 'white_id', 'white_rating', 'black_id',
       'black_rating', 'moves', 'opening_eco', 'opening_name', 'opening_ply'],
      dtype='object')

In [16]:
# Cuántas partidas gano cada uno agrupado por turnos
ganador_por_turnos = df.groupby(['winner', 'turns']).size().reset_index(name='cantidad_partidas')
print(ganador_por_turnos)

    winner  turns  cantidad_partidas
0    black      1                  2
1    black      2                108
2    black      3                 13
3    black      4                 36
4    black      5                  3
5    black      6                 26
6    black      7                  4
7    black      8                 32
8    black      9                  8
9    black     10                 44
10   black     11                 10
11   black     12                 56
12   black     13                 14
13   black     14                 71
14   black     15                 10
15   black     16                 81
16   black     17                 15
17   black     18                 84
18   black     19                 18
19   black     20                104
20   black     21                 21
21   black     22                 97
22   black     23                 20
23   black     24                114
24   black     25                 25
25   black     26                135
26   black     27                 30
27   black     28                135
28   black     29                 35
29   black     30                176
30   black     31                 30
31   black     32                162
32   black     33                 26
33   black     34                172
34   black     35                 23
35   black     36                176
36   black     37                 34
37   black     38                193
38   black     39                 34
39   black     40                230
40   black     41                 32
41   black     42                195
42   black     43                 28
43   black     44                215
44   black     45                 31
45   black     46                214
46   black     47                 33
47   black     48                223
48   black     49                 29
49   black     50                240
50   black     51                 29
51   black     52                259
52   black     53                 23
53   black     54                257
54   black     55                 30
55   black     56                242
56   black     57                 24
57   black     58                219
58   black     59                 17
59   black     60                223
60   black     61                 17
61   black     62                240
62   black     63                 16
63   black     64                202
64   black     65                 11
65   black     66                203
66   black     67                 15
67   black     68                163
68   black     69                 16
69   black     70                189
70   black     71                 16
71   black     72                162
72   black     73                 21
73   black     74                155
74   black     75                  9
75   black     76                139
76   black     77                 14
77   black     78                131
78   black     79                 11
79   black     80                143
80   black     81                 18
81   black     82                103
82   black     83                  9
83   black     84                 99
84   black     85                 11
85   black     86                 97
86   black     87                  7
87   black     88                103
88   black     89                  6
89   black     90                104
90   black     91                  1
91   black     92                101
92   black     93                  5
93   black     94                 93
94   black     95                  8
95   black     96                 95
96   black     97                  5
97   black     98                 64
98   black     99                  4
99   black    100                 68
100  black    101                  2
101  black    102                 74
102  black    104                 70
103  black    105                  4
104  black    106                 56
105  black    107                  4
106  black    108                 49
107  black    109                  3
108  black    110                 54
109  black    111                  2
110  black    112                 49
111  black    113                  2
112  black    114                 59
113  black    115                  1
114  black    116                 53
115  black    117                  2
116  black    118                 59
117  black    119                  1
118  black    120                 46
119  black    121                  2
120  black    122                 33
121  black    123                  1
122  black    124                 33
123  black    125                  4
124  black    126                 30
125  black    127                  1
126  black    128                 29
127  black    129                  4
128  black    130                 28
129  black    131                  1
130  black    132                 30
131  black    133                  2
132  black    134                 22
133  black    135                  2
134  black    136                 19
135  black    138                 22
136  black    139                  1
137  black    140                 14
138  black    141                  1
139  black    142                 20
140  black    144                 19
141  black    146                 11
142  black    148                  8
143  black    150                 19
144  black    152                 10
145  black    153                  1
146  black    154                 17
147  black    156                 11
148  black    158                  7
149  black    159                  1
150  black    160                  5
151  black    162                  5
152  black    164                  6
153  black    166                  5
154  black    168                 10
155  black    170                  8
156  black    172                  3
157  black    174                  3
158  black    176                  1
159  black    178                  3
160  black    180                  2
161  black    182                  3
162  black    184                  1
163  black    188                  2
164  black    190                  1
165  black    196                  3
166  black    198                  2
167  black    200                  1
168  black    204                  1
169  black    206                  1
170  black    210                  2
171  black    218                  1
172  black    222                  1
173   draw      2                  2
174   draw      3                 11
175   draw      4                  3
176   draw      5                  2
177   draw      6                  4
178   draw      7                  5
179   draw      8                  6
180   draw      9                  3
181   draw     10                  4
182   draw     11                  8
183   draw     12                  4
184   draw     13                  2
185   draw     14                  7
186   draw     15                  2
187   draw     16                  2
188   draw     17                  6
189   draw     18                  2
190   draw     19                  6
191   draw     20                  5
192   draw     21                  4
193   draw     22                  7
194   draw     23                  2
195   draw     24                  6
196   draw     25                  2
197   draw     26                  6
198   draw     27                  6
199   draw     28                  3
200   draw     29                  8
201   draw     30                  7
202   draw     31                  5
203   draw     32                  7
204   draw     33                 10
205   draw     34                  3
206   draw     35                  2
207   draw     36                  4
208   draw     37                  5
209   draw     38                  5
210   draw     39                  7
211   draw     40                  1
212   draw     41                  5
213   draw     42                  2
214   draw     43                 11
215   draw     44                  5
216   draw     45                  9
217   draw     46                  5
218   draw     47                  3
219   draw     48                  9
220   draw     49                  1
221   draw     50                  6
222   draw     51                  6
223   draw     52                  2
224   draw     53                  5
225   draw     54                  5
226   draw     55                  4
227   draw     56                  8
228   draw     57                 11
229   draw     58                  5
230   draw     59                  2
231   draw     60                  5
232   draw     61                  2
233   draw     62                  4
234   draw     63                 10
235   draw     64                  5
236   draw     65                  7
237   draw     66                 10
238   draw     67                  9
239   draw     68                  7
240   draw     69                  7
241   draw     70                  7
242   draw     71                  9
243   draw     72                  4
244   draw     73                 10
245   draw     74                  2
246   draw     75                  6
247   draw     76                  4
248   draw     77                  6
249   draw     78                  6
250   draw     79                  6
251   draw     80                  5
252   draw     81                  7
253   draw     82                  3
254   draw     84                  4
255   draw     85                  8
256   draw     86                 13
257   draw     87                  5
258   draw     88                 12
259   draw     89                  9
260   draw     90                  5
261   draw     91                  5
262   draw     92                  6
263   draw     93                  6
264   draw     94                  7
265   draw     95                  5
266   draw     96                  9
267   draw     97                  9
268   draw     98                  7
269   draw     99                 13
270   draw    100                 13
271   draw    101                  5
272   draw    102                  8
273   draw    103                  8
274   draw    104                 10
275   draw    105                  5
276   draw    106                  4
277   draw    107                 17
278   draw    108                  8
279   draw    109                 14
280   draw    110                  8
281   draw    111                  8
282   draw    112                  8
283   draw    113                 13
284   draw    114                 12
285   draw    115                 15
286   draw    116                  4
287   draw    117                 11
288   draw    118                  8
289   draw    119                  8
290   draw    120                  5
291   draw    121                  2
292   draw    122                 10
293   draw    123                  3
294   draw    124                  8
295   draw    125                  4
296   draw    126                  6
297   draw    127                  6
298   draw    128                  7
299   draw    129                  4
300   draw    130                 10
301   draw    131                  4
302   draw    132                  4
303   draw    133                  4
304   draw    134                  3
305   draw    135                  8
306   draw    136                  3
307   draw    137                  9
308   draw    138                  6
309   draw    139                  5
310   draw    140                  5
311   draw    141                  3
312   draw    142                  3
313   draw    143                  3
314   draw    144                  5
315   draw    145                  2
316   draw    146                  1
317   draw    147                  3
318   draw    148                  5
319   draw    149                  1
320   draw    150                  3
321   draw    151                  1
322   draw    152                  3
323   draw    153                  4
324   draw    154                  2
325   draw    155                  1
326   draw    156                  2
327   draw    157                  1
328   draw    158                  3
329   draw    159                  1
330   draw    160                  1
331   draw    161                  3
332   draw    163                  1
333   draw    164                  4
334   draw    165                  4
335   draw    167                  1
336   draw    169                  2
337   draw    170                  3
338   draw    172                  1
339   draw    173                  2
340   draw    174                  1
341   draw    177                  1
342   draw    178                  2
343   draw    179                  1
344   draw    180                  1
345   draw    181                  1
346   draw    185                  1
347   draw    187                  1
348   draw    189                  1
349   draw    190                  2
350   draw    195                  1
351   draw    200                  1
352   draw    201                  1
353   draw    205                  1
354   draw    207                  2
355   draw    208                  1
356   draw    212                  1
357   draw    216                  1
358   draw    221                  1
359   draw    222                  1
360   draw    226                  1
361   draw    255                  1
362   draw    259                  1
363  white      1                 16
364  white      2                 75
365  white      3                 63
366  white      4                 13
367  white      5                 35
368  white      6                  5
369  white      7                 61
370  white      8                 16
371  white      9                 65
372  white     10                 16
373  white     11                 78
374  white     12                 17
375  white     13                 69
376  white     14                 20
377  white     15                112
378  white     16                 27
379  white     17                112
380  white     18                 21
381  white     19                126
382  white     20                 25
383  white     21                124
384  white     22                 25
385  white     23                173
386  white     24                 32
387  white     25                134
388  white     26                 28
389  white     27                164
390  white     28                 32
391  white     29                180
392  white     30                 40
393  white     31                190
394  white     32                 34
395  white     33                198
396  white     34                 29
397  white     35                222
398  white     36                 41
399  white     37                210
400  white     38                 31
401  white     39                256
402  white     40                 37
403  white     41                258
404  white     42                 33
405  white     43                254
406  white     44                 28
407  white     45                262
408  white     46                 37
409  white     47                247
410  white     48                 27
411  white     49                236
412  white     50                 30
413  white     51                264
414  white     52                 29
415  white     53                275
416  white     54                 21
417  white     55                231
418  white     56                 21
419  white     57                262
420  white     58                 25
421  white     59                224
422  white     60                 26
423  white     61                237
424  white     62                 21
425  white     63                211
426  white     64                 22
427  white     65                208
428  white     66                 21
429  white     67                164
430  white     68                 13
431  white     69                180
432  white     70                 10
433  white     71                172
434  white     72                 14
435  white     73                167
436  white     74                 16
437  white     75                142
438  white     76                 12
439  white     77                161
440  white     78                  7
441  white     79                124
442  white     80                 10
443  white     81                130
444  white     82                 15
445  white     83                115
446  white     84                  9
447  white     85                128
448  white     86                  8
449  white     87                107
450  white     88                  2
451  white     89                111
452  white     90                  1
453  white     91                 88
454  white     92                  2
455  white     93                 82
456  white     94                  8
457  white     95                 95
458  white     96                  8
459  white     97                 62
460  white     98                  3
461  white     99                 80
462  white    100                  5
463  white    101                 83
464  white    102                  4
465  white    103                 65
466  white    104                  3
467  white    105                 67
468  white    106                  5
469  white    107                 63
470  white    108                  2
471  white    109                 59
472  white    111                 65
473  white    112                  1
474  white    113                 57
475  white    114                  2
476  white    115                 49
477  white    117                 46
478  white    118                  2
479  white    119                 53
480  white    120                  3
481  white    121                 34
482  white    122                  1
483  white    123                 42
484  white    124                  4
485  white    125                 28
486  white    127                 25
487  white    128                  2
488  white    129                 30
489  white    130                  1
490  white    131                 24
491  white    132                  1
492  white    133                 15
493  white    134                  1
494  white    135                 22
495  white    136                  2
496  white    137                 23
497  white    138                  1
498  white    139                 15
499  white    140                  1
500  white    141                 22
501  white    143                 16
502  white    145                 12
503  white    147                 14
504  white    149                 17
505  white    151                 16
506  white    153                  4
507  white    154                  1
508  white    155                 10
509  white    157                 11
510  white    159                 12
511  white    161                  9
512  white    163                  3
513  white    165                  2
514  white    167                  3
515  white    169                  4
516  white    171                  9
517  white    173                  4
518  white    175                  3
519  white    177                  1
520  white    179                  2
521  white    183                  2
522  white    185                  1
523  white    189                  3
524  white    193                  1
525  white    205                  1
526  white    209                  2
527  white    349                  2